config/routes.rb
Rails.application.routes.draw do
  # root to: 'oauth_test#index'
  root to: 'summaries#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :books do
    resources :summaries, :memos, only: [:new, :create]
    resources :reviews
  end

  resources :summaries do
    resources :comments
  end

  resources :memos, only: [:index, :edit, :show, :update, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :following, :follower
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :comment_favorites, only: [:create, :destroy]
  resources :review_favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :summary
  belongs_to :user
  has_many :comment_favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :content, presence: true

  def self.calc_level(current_user)
    current_user.summaries.count * 0.8 + current_user.memos.count * 0.3 + current_user.reviews.count * 0.1 + current_user.comments.count * 0.1
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_summary, only: [:create, :edit, :update]
  before_action :authenticate_user!

  def create
    @summary = Summary.find(params[:summary_id])
    @comment = @summary.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        @summary.create_notification_comment!(current_user, @comment.id)
        read_level = Comment.calc_level(current_user)
        current_user.update(level: read_level.floor)
        format.js { render :index }
      else
        format.html { redirect_to summary_path(@summary) }
      end
    end
  end

  def edit
    @comment = @summary.comments.find(params[:id])
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def update
    @comment = @summary.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render :index }
      else
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    read_level = Comment.calc_level(current_user)
    current_user.update(level: read_level.floor)
    respond_to do |format|
      format.js { render :index }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:summary_id, :content)
  end

  def set_summary
    @summary = Summary.find(params[:summary_id])
  end
end

app/views/comments/_edit.html.erb
<%= form_with(model: [summary, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="edit-review">
    <%= form.text_area :content, id: "comment_content_#{summary.id}", class: 'form-control' %>
  </div>
  <div class="actions">
    <p><%= form.submit value=t('view.update'), class: 'comment-submit' %></p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [summary, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <% comment.errors.full_messages.each do |message| %>
        <h3><%= message %></h3>
      <% end %>
    </div>
  <% end %>
  <div class="review-text-area">
    <p><%= form.text_area :content, class: 'form-control', placeholder:t('view.create_comment') %></p>
  </div>
  <div class="actions">
    <p><%= form.submit value=t('view.submit'), class: 'comment-submit' %></p>
  </div>
<% end %>

app/views/comments/_index.html.erb
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <div class="review-range">
        <div class="left-review">
          <p class="review-user small-icon">
            <% if comment.user.icon? %>
              <%= image_tag(comment.user.icon.url, :size =>'30x30')  %>
            <% else %>
              <%= image_tag("favicon.ico", :size =>'30x30') %>
            <% end %>
            <%= link_to comment.user.name, user_path(comment.user) %>
          </p>
          <p class="review-user-content"><%= comment.content %></p>
          <div id="likes_buttons_<%= comment.id %>" class="like-btn">
            <h4><%= render partial: 'comment_favorites/like', locals: { comment: comment} %><%= comment.comment_favorites.count %></h4>
          </div>
        </div>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <% if comment.user_id == current_user.id%>
          <div class="right-review">
            <%= link_to fa_icon("edit lg"), edit_summary_comment_path(summary, comment), remote: true %>　
            <%= link_to fa_icon("trash-alt lg"), summary_comment_path(comment.summary_id, comment.id), method: :delete, remote: true, data: { confirm: t('view.are_you_sure') } %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', summary: @summary, comment: @comment %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.summary.comments.order(created_at: :desc), summary: @comment.summary }) %>")
$("textarea").val('')