config/routes.rb
Rails.application.routes.draw do
  # root to: 'oauth_test#index'
  root to: 'summaries#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :books do
    resources :summaries, :memos, only: [:new, :create]
    resources :reviews
  end

  resources :summaries do
    resources :comments
  end

  resources :memos, only: [:index, :edit, :show, :update, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :following, :follower
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :comment_favorites, only: [:create, :destroy]
  resources :review_favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :summary, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="notice-block">
  <% if visitor.icon? %>
    <%= image_tag(visitor.icon.url, :size =>'23x23')  %>
  <% else %>
    <%= image_tag("favicon.ico", :size =>'23x23') %>
  <% end %>
    <%= link_to visitor.name, user_path(visitor) %><%= "さんが" %>

  <% if notification.action == "follow" %>
    <%= "あなたをフォローしました"%>
  <% elsif notification.action == "like" %>
    <%= link_to "あなたの投稿", summary_path(notification.summary) %>
    <%= "にいいねしました" %>
  <% else %>
    <% if notification.summary.user_id == visited.id %>
      <%= link_to "あなたの投稿", summary_path(notification.summary) %>
    <% else %>
        <% if visitor.icon? %>
          <%= image_tag(visitor.icon.url, :size =>'20x20')  %>
        <% else %>
          <%= image_tag("favicon.ico", :size =>'20x20') %>
        <% end %>
        <%= link_to notification.summary.user.name, user_path(notification.summary.user) %><%= "さんの投稿" %>
    <% end %>
    <%= "にコメントしました" %>
    <p class="notice-comment"><%= Comment.find_by(id: notification.comment_id)&.content %></p>
  <% end %>
</div>