config/routes.rb
Rails.application.routes.draw do
  # root to: 'oauth_test#index'
  root to: 'summaries#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :books do
    resources :summaries, :memos, only: [:new, :create]
    resources :reviews
  end

  resources :summaries do
    resources :comments
  end

  resources :memos, only: [:index, :edit, :show, :update, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :following, :follower
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :comment_favorites, only: [:create, :destroy]
  resources :review_favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book, only: [:create, :edit, :update]
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.build(review_params)
    @review.user_id = current_user.id
    respond_to do |format|
      if @review.save
        read_level = Review.calc_level(current_user)
        current_user.update(level: read_level.floor)
        format.js { render :index }
      else
        format.html { redirect_to book_path(@book) }
      end
    end
  end

  def edit
    @review = @book.reviews.find(params[:id])
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def update
    @review = @book.reviews.find(params[:id])
      respond_to do |format|
        if @review.update(review_params)
          format.js { render :index }
        else
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    read_level = Review.calc_level(current_user)
    current_user.update(level: read_level.floor)
    respond_to do |format|
      format.js { render :index }
    end
  end

  private
  def review_params
    params.require(:review).permit(:book_id, :content)
  end

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/views/reviews/_edit.html.erb
<%= form_with(model: [book, review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="edit-review">
    <%= form.text_area :content, id: "review_content_#{book.id}", class: 'form-control' %>
  </div>
  <div class="actions">
    <p><%= form.submit value=t('view.update'), class: 'review-submit' %></p>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: [book, review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="review-text-area">
    <p><%= form.text_area :content, class: 'form-control', placeholder: t('view.create_review') %></p>
  </div>
  <div class="actions">
    <p><%= form.submit value=t('view.submit'), class: 'review-submit' %></p>
  </div>
<% end %>

app/views/reviews/_index.html.erb
<% reviews.each do |review| %>
  <% if review.id.present? %>
    <div class="review-range">
      <div class="left-review">
        <p class="review-user small-icon">
          <% if review.user.icon? %>
            <%= image_tag(review.user.icon.url, :size =>'30x30')  %>
          <% else %>
            <%= image_tag("favicon.ico", :size =>'30x30') %>
          <% end %>
          <%= link_to review.user.name, user_path(review.user) %>
        </p>
        <p class="review-user-content"><%= review.content %></p>
        <div id="likes_buttons_<%= review.id %>" class="like-btn">
            <h4><%= render partial: 'review_favorites/like', locals: { review: review} %><%= review.review_favorites.count %></h4>
          </div>
      </div>
      <div class="review-content" id ="this_review_<%= review.id %>"></div>
      <% if review.user_id == current_user.id%>
        <div class="right-review">
          <%= link_to fa_icon("edit lg"), edit_book_review_path(book, review), remote: true %>　
          <%= link_to fa_icon("trash-alt lg"), book_review_path(review.book_id, review.id), method: :delete, remote: true, data: { confirm: t('view.are_you_sure')} %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/reviews/edit.js.erb
$("#this_review_<%= @review.id %>").replaceWith("<%= j render 'reviews/edit', book: @book, review: @review %>");

app/views/reviews/index.js.erb
$("#reviews_area").html("<%= j(render 'reviews/index', { reviews: @review.book.reviews.order(created_at: :desc), book: @review.book }) %>")
$("textarea").val('')