config/routes.rb
Rails.application.routes.draw do
  # root to: 'oauth_test#index'
  root to: 'summaries#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :books do
    resources :summaries, :memos, only: [:new, :create]
    resources :reviews
  end

  resources :summaries do
    resources :comments
  end

  resources :memos, only: [:index, :edit, :show, :update, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :following, :follower
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :comment_favorites, only: [:create, :destroy]
  resources :review_favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :content, presence: true
  validates :action_plan, presence: true
  validates :email_send, inclusion: [true, false]

  def self.calc_level(current_user)
    current_user.summaries.count * 0.8 + current_user.memos.count * 0.3 + current_user.reviews.count * 0.1 + current_user.comments.count * 0.1
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @memo = Memo.new
    @book = Book.find(params[:book_id])
    category = @book.summaries.pluck(:category)
    if category.count < 1
      @category_1 = @book.summaries.categories_i18n.first[1]
    elsif category.count < 2
      @category_1 = @book.summaries.first.category_i18n
    elsif category.count < 3
      @category_1 = @book.summaries.first.category_i18n
      @category_2 = @book.summaries.second.category_i18n
    else
      @category_1 = @book.summaries.first.category_i18n
      @category_2 = @book.summaries.second.category_i18n
      @category_3 = @book.summaries.third.category_i18n
    end
  end

  def create
    @book = Book.find(params[:book_id])
    @memo = @book.memos.build(memo_params)
    @memo.user_id = current_user.id
    if @memo.save
      UserMailer.notify_user().deliver
      read_level = Memo.calc_level(current_user)
      current_user.update(level: read_level.floor)
      redirect_to summaries_path, notice: t('view.create_notice')
    else
      render :new
    end
  end


  def show
    category = @memo.book.summaries.pluck(:category)
    if category.count < 1
      @category_1 = @memo.book.summaries.categories_i18n.first[1]
    elsif category.count < 2
      @category_1 = @memo.book.summaries.first.category_i18n
    elsif category.count < 3
      @category_1 = @memo.book.summaries.first.category_i18n
      @category_2 = @memo.book.summaries.second.category_i18n
    else
      @category_1 = @memo.book.summaries.first.category_i18n
      @category_2 = @memo.book.summaries.second.category_i18n
      @category_3 = @memo.book.summaries.third.category_i18n
    end
  end

  def edit
    @book = @memo.book
    category = @book.summaries.pluck(:category)
    if category.count < 1
      @category_1 = @book.summaries.categories_i18n.first[1]
    elsif category.count < 2
      @category_1 = @book.summaries.first.category_i18n
    elsif category.count < 3
      @category_1 = @book.summaries.first.category_i18n
      @category_2 = @book.summaries.second.category_i18n
    else
      @category_1 = @book.summaries.first.category_i18n
      @category_2 = @book.summaries.second.category_i18n
      @category_3 = @book.summaries.third.category_i18n
    end
  end

  def update
    if @memo.update(memo_params)
      UserMailer.notify_user().deliver
      redirect_to memo_path(@memo), notice: t('view.edit_notice')
    else
      @book = @memo.book
      render :edit
    end
  end

  def destroy
    @memo.destroy
    UserMailer.notify_user().deliver
    read_level = Memo.calc_level(current_user)
    current_user.update(level: read_level.floor)
    redirect_to user_path(current_user), notice: t('view.destroy_notice')
  end

  private
  def memo_params
    params.require(:memo).permit(:content, :action_plan, :email_send)
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end
end

app/views/memos/edit.html.erb
<div class="container">
  <%= form_with(model: @memo, local: true) do |form| %>
    <% if @memo.errors.any? %>
      <div id="error_explanation">
        <% @memo.errors.full_messages.each do |message| %>
          <h4><%= message %></h4>
        <% end %>
      </div>
    <% end %>

    <table class="book-show-table">
      <tr class="book-detail">
        <td class="book-image">
          <%= image_tag(@book.image_url) %>
        </td>
        <td class="book-desc">
          <p>
            <span class="book-title"><%= t('view.title') %>　</span>
            <span class="book-ex"><%= @book.title %></span>
          </p>
          <p>
            <span class="book-title"><%= t('view.genre') %>　</span>
            <span class="book-ex">
                <%= @category_1 %>
              <% if @category_2 && @category_1 != @category_2 &&  @category_2 != @category_3%>
                ,　<%= @category_2 %>
              <% end %>
              <% if @category_3 && @category_1 != @category_3 &&  @category_2 != @category_3 %>
                ,　<%= @category_3 %>
              <% end %>
            </span>
          </p>
          <p>
            <span class="book-title"><%= t('view.author') %>　　　</span>
            <span class="book-ex"><%= @book.author %></span>
          </p>
          <p>
            <span class="book-title"><%= t('view.publisher') %>　　</span>
            <span class="book-ex"><%= @book.publisher %></span>
          </p>
          <p class="notice">
            <span><%= form.label :email_send, "通知" %>　　　</span>
            <span>
              <%= form.hidden_field :email_send, value: false %>
              <%= form.check_box :email_send, {}, true, false %>
            </span>
          </p>
        </td>
      </tr>
    </table>

    <hr>

    <table class="memo-table center">
      <tr class="">
        <td>
          <p class="title-memo"><%= t('view.memo') %></p>
        </td>
        <td>
          <p class="title-action-plan"><%= t('view.action_plan') %></p>
        </td>
      </tr>
    </table>

    <div class="memo-block">
      <div class="memo__element1">
        <%= form.hidden_field :content, id: 'post_content' %>
        <trix-editor id="memo_content" input="post_content"></trix-editor>
      </div>

      <div class="memo__element2">
      </div>

      <div class="memo__element3">
        <%= form.hidden_field :action_plan, id: 'post_action' %>
        <trix-editor id="memo_action_plan" input="post_action"></trix-editor>
      </div>
    </div>

    <hr>

    <div class="center">
      <%= form.submit t('view.update'), class:"search-submit" %>
    </div>

    <br>
    <br>
    <br>
  <% end %>
</div>

app/views/memos/new.html.erb
<div class="container">
  <%= form_with(model: [@book, @memo], local: true) do |form| %>
    <% if @memo.errors.any? %>
      <div id="error_explanation">
        <% @memo.errors.full_messages.each do |message| %>
          <h4><%= message %></h4>
        <% end %>
      </div>
    <% end %>

    <table class="book-show-table">
      <tr class="book-detail">
        <td class="book-image">
          <%= image_tag(@book.image_url) %>
        </td>
        <td class="book-desc">
          <p>
            <span class="book-title"><%= t('view.title') %>　</span>
            <span class="book-ex"><%= @book.title %></span>
          </p>
          <p>
            <span class="book-title"><%= t('view.genre') %>　</span>
            <span class="book-ex">
                <%= @category_1 %>
              <% if @category_2 && @category_1 != @category_2 &&  @category_2 != @category_3%>
                ,　<%= @category_2 %>
              <% end %>
              <% if @category_3 && @category_1 != @category_3 &&  @category_2 != @category_3 %>
                ,　<%= @category_3 %>
              <% end %>
            </span>
          </p>
          <p>
            <span class="book-title"><%= t('view.author') %>　　　</span>
            <span class="book-ex"><%= @book.author %></span>
          </p>
          <p>
            <span class="book-title"><%= t('view.publisher') %>　　</span>
            <span class="book-ex"><%= @book.publisher %></span>
          </p>
          <p class="notice">
            <span><%= form.label :email_send, t('view.notice') %>　　　</span>
            <span>
              <%= form.hidden_field :email_send, value: false %>
              <%= form.check_box :email_send, {}, true, false %>
            </span>
          </p>
        </td>
      </tr>
    </table>

    <hr>

    <table class="memo-table center">
      <tr class="">
        <td>
          <p class="title-memo"><%= t('view.memo') %></p>
        </td>
        <td>
          <p class="title-action-plan"><%= t('view.action_plan') %></p>
        </td>
      </tr>
    </table>

    <div class="memo-block">
      <div class="memo__element1">
        <%= form.hidden_field :content, id: 'post_content' %>
        <trix-editor id="memo_content" input="post_content"></trix-editor>
      </div>

      <div class="memo__element2">
      </div>

      <div class="memo__element3">
        <%= form.hidden_field :action_plan, id: 'post_action' %>
        <trix-editor id="memo_action_plan" input="post_action"></trix-editor>
      </div>
    </div>

    <hr>

    <div class="center">
      <%= form.submit t('view.submit'), class:"search-submit" %>
    </div>

    <br>
    <br>
  <% end %>
</div>

app/views/memos/show.html.erb
<div class="container">
  <table class="book-show-table">
    <tr class="book-detail">
      <td class="book-image">
        <%= link_to image_tag(@memo.book.image_url), book_path(@memo.book)%>
      </td>
      <td class="book-desc">
        <p>
          <span class="book-title"><%= t('view.title') %>　</span>
          <span class="book-ex"><%= link_to @memo.book.title, book_path(@memo.book) %></span>
        </p>
        <p>
          <span class="book-title"><%= t('view.genre') %>　</span>
          <span class="book-ex">
              <%= @category_1 %>
            <% if @category_2 && @category_1 != @category_2 &&  @category_2 != @category_3%>
              ,　<%= @category_2 %>
            <% end %>
            <% if @category_3 && @category_1 != @category_3 &&  @category_2 != @category_3 %>
              ,　<%= @category_3 %>
            <% end %>
          </span>
        </p>
        <p>
          <span class="book-title"><%= t('view.author') %>　　　</span>
          <span class="book-ex"><%= @memo.book.author %></span>
        </p>
        <p>
          <span class="book-title"><%= t('view.publisher') %>　　</span>
          <span class="book-ex"><%= @memo.book.publisher %></span>
        </p>
        <% if current_user == @memo.user%>
        <p>
          <span class="book-title"><%= t('view.notice') %>　　　</span>
          <span class="book-ex">
            <% if @memo.email_send == true %>
              <%= "ON" %>
            <% else %>
              <%= "OFF" %>
            <% end %>
          </span>
        </p>
        <% end %>
      </td>
    </tr>
  </table>

  <hr>

  <table class="memo-table center">
    <tr class="">
      <td>
        <p class="title-memo"><%= t('view.memo') %></p>
      </td>
      <td>
        <p class="title-action-plan"><%= t('view.action_plan') %></p>
      </td>
    </tr>
  </table>

  <div class="memo-block">
    <div class="block__element1">
      <p class="trix"><%= sanitize @memo.content %></p>
    </div>

    <div class="block__element2">
    </div>

    <div class="block__element3">
      <p class="trix"><%= sanitize @memo.action_plan %></p>
    </div>
  </div>

  <% if @memo.user_id == current_user.id%>
    <div class="right-review">
      <%= link_to fa_icon("edit 2x"), edit_memo_path(@memo) %>　
      <%= link_to fa_icon("trash-alt 2x"), @memo, method: :delete, data: { confirm: t('view.are_you_sure') } %>
    </div>
  <% end %>

  <br>
  <br>
  <br>
</div>